<?php

class Mahasiswa
{
    function getMahasiswaKuper()
    {
        return [
            'FADEL SYAHBANA TAMRAN PUTRA',
            'BRILIAN ANUGRA',
            'DIMAS PANGESTU EXWANTHO',
            'GIERALD RIHHADAT E F',
            'MUHAMMAD ALDI MAHENDRA GUNADI',
            'ALDI RIZKI',
            'ANDRI A.HAFID',
            'ARYA NUGRAHA',
            'LEONY AYU PARAMITA',
            'RADEN DWI ANTIKA KESUMA',
            'ANGGARA EKA SAPUTRA',
            'ANANG BIMA PERDANA',
            'RIZKY RAMADHAN',
            'WISDAH EFENDI',
            'MAULANA HUSAINI',
            'PATRIA SATRIDWI PANGGA',
            'AJI MUKTI WIJAYA',
            'AGUNG DWI CAHYO',
            'NOVALIA GITA RAMADHANI',
            'MIFTAHUL RAHMAH',
            'DEVHA OKTAVERHIA',
            'ANDRE NOVIAN',
            'REGITA BENING KUSUMA',
            'DONI GAGAH PRAMUDYA',
            'AFRIALDI SAPUTRA',
            'ANGGARA PUTRA PRADANA APRIANSYAH',
            'NADIA WATI APRIANTI',
            'LEGI ADI PRAMANA',
            'ABDURAHMAN ALGIFARI',
            'ZIDAN ZULKHAIRYAN MANDALIM',
            'M. MIFTAHUS SALAM',
            'DARLIAN RAMADHANI',
            'LA ALHADAR ROHAN',
            'MURDIFIN',
            'RADITYA ADI NUGRAHA',
            'NANDA AJI NUGROHO',
            'NOVELIA NUR ILLAHI',
            'MUH. SATRIYO ADINUL HABIB',
            'RAFI FAKHTUR RAHMAN',
            'DITO ABDUSALAM RAFI',
            'WAHYU DWI RAMADHANDI',
            'AZWAR SHOLEH',
            'TRI SURYO WAHYU AJI',
            'MUHAMMAD NUR ADLI',
            'RADEN RARA KURNIA RIZKYANI HENDARTO',
            'JESICHA HETY MANIKA',
            'LEZZA GIGIH PRASETYA PUTRA',
            'RAIHANI RAMBE',
            'MUHAMMAD TAUFIQ INSANI',
            'PUTRI AYU DARUNINGTYAS',
            'KHAIRUL AMRI',
            'FARID AFGAR',
            'MUHAMMAD IRFAI ',
            'TIA IKLIMA',
            'WULAN NIKEN SARI',
            'GUNTUR GENTA RAMADHAN ',
            'FERDI SETIADI',
            'EDO KURNIAWAN ',
            'HERDIN ASMARA TIMOR',
            'FARIZ HINDAMI ALGIFARI ',
            'FADEL NUR AKHMAD',
            'ANZALA AHMAD SAUQI',
            'ABIYYI RIZKI FERANTO ERAWAN',
            'AULIA RAHMAN NASUTION',
            'WISNU ANDRIAN'
        ];
    }

    function getMahasiswaTesi()
    {
        return [
            'M. SATRIO AJI',
            'FADEL SYAHBANA TAMRAN PUTRA',
            'FIRMAN',
            'NURMUTMAINAH',
            'MUHAMAD RESTU ADJI PRATAMA',
            'WENDRY ARYA ERLANGGA',
            'RACHMAN ANDIKA PUTRA',
            'ANDIKA PRIH PAMUNGKAS',
            'MUHAMMAD TAQIY RIZQILLAH',
            'ANDRE NOVIAN',
            'DIMAS AHMAD',
            'MUHAMMAD YUSUF',
            'ABDURAHMAN ALGIFARI',
            'FERHAT MUHAMAD YASIN',
            'DEDEN NURHIDAYAT',
            'EGA GILANG MAHENDRA',
            'AJI NUGROHO LIWANTO',
            'ARISDA DWI PUTRI',
            'YOSYADI RIZKIKA AMANATULLAH. S',
            'MIFTAHULZEN AL ASYARI ',
            'DAFIAN HAMMAS ASHSHIDQI YADHITAMA ',
            'RADITYA ADI NUGRAHA ',
            'SEFTIAN HADI NUGROHO',
            'IRMA ERYANTI PUTRI',
            'HAVINDI FAHRU MILEANSYAH',
            'FESA WAHYU NINGSIH',
            'ANGELIA RETNO MADYANINGRUM',
            'TRI SURYO WAHYU AJI',
            'LAZUARDI FIRDAUS',
            'NADYA ESTIYANA KHAIRUNNISHA',
            'RAIHANI RAMBE',
            'FINKA KURNILA MAWARDINI',
            'AUDREY FLORENZORA SHELMAVEDA',
            'YUSRIL MAHENDRI',
            'MUHAMMAD IRFAI ',
            'WULAN NIKEN SARI',
            'ALDI FEBRIANTO',
            'MUHAMMAD DAFFIANO RAHMATULLAH',
            'BASYID FARHAN MURSYIDAN',
            'M.SYAIFULLAH',
            'IMAM MUBARAQ',
            'RADITYA PANGESTIKA DENTA AREZHA',
            'M. JORDAN BRILIAN',
            'BAGUS MAULANA',
            'NAFISAH RAHMAWATI',
            'IKHSAN ADITYA NUUR QODRI',
            'TRI CAHYO LAKSONO',
            'M.AFIF ABDILLAH',
            'ARVIN DESTANTYA RYANANDRA RAMADHAN',
            'M. FAJAR KHAERUL ANAM',
            'BURHANU SULTAN RAMADAN',
            'MOHAMMAD ALDI ROSYIDIN',
            'AIDIEHL FITRA ROZIE',
            'BRILLY JALU KUMARA BISEKA',
            'FAIQ SUHAIL',
            'MUHAMMAD YUSRIL ANANTA',
            'SABILLA ROSYADA',
            'FADHIL AL HAFIZH IBTA',
            'FARHAN ARIO ALTARIQ',
            'FACHRY RAHMAN HAKIM',
            'MUHAMMAD ILHAM AQLI DILAN',
            'AULIA RAHMAN NASUTION',
            'MUHAMMAD ALTHOOFANDY SUPRAYOGI',
            'AZHAR SYAHID'
        ];
    }
}
